---
collections:
  - name: ansible.controller
    source: https://console.redhat.com/api/automation-hub/content/published/
  - community.general
roles:
  - name: role_aap_controller_setup
    src: https://github.com/kubealex/role_aap_controller_setup.git
  - name: role_eda_controller_setup
    src: https://github.com/kubealex/role_eda_controller_setup.git
