aap2_controller_url:
aap2_controller_username:
aap2_controller_password:

eda_controller_url:
eda_controller_user:
eda_controller_password:

servicenow_instance_url:
servicenow_instance_username:
servicenow_instance_password:

openshift_api_url:
openshift_admin_username:
openshift_admin_password:

rhsm_account_username:
rhsm_account_password:

dynatrace_url:
dynatrace_token:
