apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vm-metrics
  namespace: demo-vm
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: http
  selector:
    matchLabels:
      servicetype: metrics
