apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-config
  namespace: openshift-cnv
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens4
        description: Linux bridge with ens9 as a port
        ipv4:
          enabled: false
        name: br1
        state: up
        type: linux-bridge
