kind: ConfigMap
apiVersion: v1
metadata:
  name: engine-monitor
immutable: false
data:
  config.yaml: |-
    ---
    bootstrap-servers: "kafka-ephemeral-single-kafka-bootstrap:9092"
    topic: "sensors"
    #security-protocol: "sasl_ssl"
    #sasl-mechanisms: "PLAIN"
    #sasl-username: ""
    #sasl-password: ""

