apiVersion: v1
kind: Service
metadata:
  name: engine-monitor
  namespace: rh-sc23-eda-edge
spec:
  selector:
    app: engine-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
