FROM registry.redhat.io/rhel9/go-toolset:1.19.10-14.1696536543 as builder

WORKDIR /app
USER root
COPY main.go go.mod go.sum .
RUN go build .

FROM registry.access.redhat.com/ubi9/ubi-minimal

RUN mkdir /app
COPY --from=builder /app/engine-monitor /app

RUN chgrp -R 0 /app && \
    chmod -R g+rwx /app/engine-monitor

USER 1001

WORKDIR /app

ENTRYPOINT ["./engine-monitor"]

