---
- name: EDA | Insights | Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: EDA | Insights | Detect and remediate CVE event from Insights
      condition: event.payload.event_type == "new-advisory"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA][Insights] Handle Advisories"
            organization: Default
            job_args:
              extra_vars:
                insights_advisories: "{{ event.payload.events }}"
                insights_advisories_context: "{{ event.payload.context }}"
                target_hosts: "{{ event.payload.context.display_name }}"
