---
- name: EDA | AlertManager | Listen for events from AlertManager and open ITSM ticket
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: EDA | AlertManager | Handle OCPVirtLowDisk alert from OCP
      condition: event.payload.status == "firing" and event.payload.commonLabels.source == "ocp" and event.payload.commonLabels.alertname == "OCPVirtLowDisk"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA][Alertmanager][OCP] - Report OCPVirtLowDisk alert"
            organization: Default
            set_facts: true
            job_args:
              extra_vars:
                alerts: "{{ event.payload.alerts }}"
                alertStatus: "{{ event.payload.status }}"
        - run_job_template:
            name: "[EDA][Alertmanager][OCP] - Resolve OCPVirtLowDisk alert"
            organization: Default
            set_facts: true

    - name: EDA | AlertManager | Handle OCPVirtLowDisk alert resolution from OCP
      condition:
        all:
          - facts.incident_number is defined
          - event.payload.status == "resolved" and event.payload.commonLabels.source == "ocp" and event.payload.commonLabels.alertname == "OCPVirtLowDisk"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA][Alertmanager][OCP] - Report OCPVirtLowDisk alert"
            organization: Default
            set_facts: true
            job_args:
              extra_vars:
                ticket_number: "{{ events.m_0.incident_number }}"
                alertStatus: "{{ events.m_1.payload.status }}"
                alerts: "{{ events.m_1.payload.alerts }}"
