---
- name: EDA | Kafka | Listen for events on a Kafka topic
  hosts: localhost

  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_host | default('localhost', true) }}"
        port: "{{ kafka_port | default('9092', true) }}"
        topic: "{{ kafka_topic | default('sensors', true) }}"

  rules:
    - name: EDA | Kafka | Handle frequence anomaly
      condition: event.body.offset_vibration >= '201'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA][Kafka] Shutdown Engine"
            organization: Default
            job_args:
              extra_vars:
                vibration_rate: "{{ event.body.offset-vibration }}"

        - run_job_template:
            name: "[EDA][Kafka] Report enginge shutdown with a ticket"
            organization: Default
            job_args:
              extra_vars:
                incident_short_description: |
                  "Anomaly reported on Engine"
                incident_description: |
                  Potential engine failure happening, anomaly on vibration rate.
                  Reported vibration rate: "{{ event.body.offset_vibration }}
                  Engine was shut down to avoid damage, requires an inspection ASAP.
