---
- name: EDA | Kafka | Handle machine shutdown
  hosts: localhost
  tasks:
    - name: EDA | Kafka | Send shutdown signal
      ansible.builtin.uri:
        url: "{{ engine_monitor_endpoint | default('http://engine-monitor.rh-sc23-eda-edge.svc:8080') }}/shutdown"
        method: POST
        status_code:
          - 200
          - 201
        body:
          status: shutdown
        body_format: json

    - name: EDA | Kafka | Acknowledge shutdown
      ansible.builtin.debug:
        msg:
          - "Engine shutdown successful"
