---
- name: EDA | Kafka | Handle machine shutdown
  hosts: localhost
  tasks:
    - name: EDA | Kafka | Send shutdown signal
      ansible.builtin.uri:
        url: "{{ endpoint }}"
        method: POST
        status_code:
          - 200
          - 201
        body:

        body_format: json

    - name: EDA | Kafka | Acknowledge shutdown
      ansible.builtin.debug:
        msg: XXX
